name: Shopify Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Set PR number
        id: vars
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Deploy to theme
        run: |
          THEME_NAME="PR #${PR_NUMBER}"
          
          # Use SHOPIFY_FLAG_STORE from environment variable
          THEME_ID=$(shopify theme list | grep "$THEME_NAME" | awk '{print $1}')

          if [ -z "$THEME_ID" ]; then
            # Use SHOPIFY_FLAG_STORE from environment variable
            CREATED_THEME_OUTPUT=$(shopify theme create "$THEME_NAME" --json)
            CREATED_THEME_ID=$(echo "$CREATED_THEME_OUTPUT" | jq -r '.id')
            shopify theme push \
              --json \
              --theme-id "$CREATED_THEME_ID"
          else
            shopify theme push \
              --json \
              --theme-id "$THEME_ID"
          fi
            
        env:
          SHOPIFY_CLI_THEME_TOKEN: shptka_63b498d336592addc4ba09b232f4a344
          SHOPIFY_FLAG_STORE: nine-pillars.myshopify.com 
